###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: a
            MYSQL_DATABASE: a
            MYSQL_USER: a
            MYSQL_PASSWORD: a
        ports:
            - "8003:3306"

    webserver:
        image: 'nginx:alpine'
        working_dir: /var/www
        volumes:
            - '.:/var/www'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8001:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /var/www
        volumes:
            - '.:/var/www'
            - './storage/logs:/var/www/storage/logs'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
