###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:5.7'
        working_dir: /www
        volumes:
            - '..:/www'
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=quiz
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=secret
        ports:
            - '8003:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /www
        volumes:
            - '..:/www'
            - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8001:80'

    php-fpm:
        build: php-fpm
        working_dir: /www
        volumes:
            - '..:/www'
            - './php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
